### ISSUE TITLE
Roll out from beta

### ISSUE THREAD

**Issue by antfu** [antfu/vueuse#166]
Since Vue 3 has officially released for a while now. I think it's time for us to roll out from beta aim for a stable release.

Checklist

- [x] Review functions, frozen the APIs (consistency, flexibility, simplicity)
	- It should be our last chance (at this phrase) to introduce breaking changes to the existing functions. Breaking changes should be working on the dev branch.
    - [x] Make global reference configurable #184 
	- [x] Docs should not contain JSX, `@vue/composition-api`, `vue-demi`, etc.
    - [x] JSX docs #183
    - [x] Filters system #192  
- [x] Unit-tests for utilties as possible
	- It's ok for not having tests for simple web API wrappers.
- [x] Setup bundle size GitHub Actions via [export-size](https://github.com/antfu/export-size)
- [x] Demo rewrites working by @anteriovieira

## Functions

- [x] **useStorage**: debounce
- [x] **useShare**: returns a function instead of call it immediately, #176 

## Docs 

Preview: https://dev--vueuse.netlify.app/

- [x] Path redirecting, support short link like [vueuse.js.org/useMouse](https://dev--vueuse.netlify.app/useMouse)
- [x] Write a doc about how to use the functions #191 
	- [x] reactive to unwrap the refs
    - [x] configurable window, document
    - [x] timing
    - [x] filter system
## Preview Opt-in (Nightly Builds)

[npm package](https://www.npmjs.com/package/@knightly/vueuse/v/dev), powered by [![Nightly Build](https://github.com/antfu/knightly/blob/main/res/badge.svg?raw=true)](https://github.com/antfu/knightly)

To replace the package with nightly build:

via npm

```
npm i @vueuse/core@npm:@knightly/vueuse@dev
```

or edit your package.json

```json
"dependencies": {
  "@vueuse/core": "npm:@knightly/vueuse@dev"
}
```

## New Features

- New @vueuse/router package

- Event filter system

- `pausableWatch`, `debouncedWatch`, `thottledWatch`, `watchWithFilter`

### BREAKING CHANGE

<details>
<summary>
<b><code>useTransition</code></b> - named transition presets are removed. Import them from <code>TransitionPresets</code> intead. #190 
</summary>

<br>

```ts
import { useTransition } from '@vueuse/core'

useTransition(baseNumber, {
  duration: 1000,
  transition: 'easeInOutCubic',
})
```

Changed to
 
```ts
import { useTransition, TransitionPresets } from '@vueuse/core'

useTransition(baseNumber, {
  duration: 1000,
  transition: TransitionPresets.easeInOutCubic,
})
```
</details>

<details>
<summary>
<b><code>asyncComputed</code></b> - evaluating state is now passed through arguments instead of returning tuple
</summary>

<br>

```ts
import { asyncComputed } from '@vueuse/core'

const [state, evaluating] = asyncComputed(async () => {}, {})
```

Changed to
 
```ts
import { asyncComputed } from '@vueuse/core'

const evaluating = ref(false)
const state = asyncComputed(async () => {}, {}, evaluating)
```
</details>

<details>
<summary>
<b><code>useEventListener</code></b> - event target moved from 4th argument to first
</summary>

<br>

```ts
import { useEventListener } from '@vueuse/core'

useEventListener('click', handler, undefined, document)
```

Changed to
 
```ts
import { useEventListener } from '@vueuse/core'

useEventListener(document, 'click', handler)
```
</details>

<details>
<summary>
<b><code>useRefHistory</code></b> - `flush` now default to `pre`, returned `current` renamed to `source`, hisotry point `value` renamed to `snapshot`
</summary>

<br>
Refer to docs for more details.
</details>

<details>
<summary>
<b><code>useWebWorkerFn</code></b> - `workerStatus` changed from enum to literal unions
</summary>

<br>

```ts
import { useWebWorkerFn, WorkStatus } from '@vueuse/core'

const { workerStatus } = useWebWorkerFn(fn)

workerStatus.value === WorkStatus.running
```

Changed to
 
```ts
import { useWebWorkerFn } from '@vueuse/core'

const { workerStatus } = useWebWorkerFn(fn)

workerStatus.value === 'RUNNING'
```
</details>

<details>
<summary>
<b><del><code>useNow</code></del></b> - `useNow` renamed to `useTimestamp` with API changes
</summary>

<br>

```ts
import { useNow } from '@vueuse/core'

const now = useNow()
```

Changed to
 
```ts
import { useTimestamp } from '@vueuse/core'

const { timestamp: now, pause, resume } = useTimestamp()
```
</details>

<details>
<summary>
<b><del><code>useRaf</code></del></b> - dropped in favor of `useTimestamp`
</summary>

<br>
None
</details>

<details>
<summary>
<b><code>useTimeout / useInterval</code></b> - returned `activated` renamed to `isActive`
</summary>

<br>
None
</details>

<details>
<summary>
<b><code>useRafFn</code></b> - `start` / `stop` renamed to `resume` / `pause`
</summary>

<br>
None
</details>

<details>
<summary>
<b><code>useXXXObserver</code></b> - API changes
</summary>
<br>

Refer to docs and types for more details.
</details>

**Comment by scottbedard** [comment]
@antfu If you're willing to introduce a breaking change, I sort of regret including named presets with the [`useTransition`](https://vueuse.js.org/?path=/story/animation--usetransition) function. The ability fo define a cubic bezier curve or a transition function is still very flexible and easy to use IMO. I never find myself reaching for the named transitions. Defining the curve yourself lets it live in your source control, rather than just having some magic string. Also, I can't imagine a situation where anyone would need that many named presets, so it's just unnecessary bloat.

**Comment by antfu** [comment]
@scottbedard Sure! But instead of remove all the presets, maybe we could split them into another export. Meaning:

```ts
import { useTransition } from '@vueuse/core'

useTransition(baseNumber, {
  duration: 1000,
  transition: 'easeInOutCubic',
})
```

To

```ts
import { useTransition, TransitionPresets } from '@vueuse/core'

useTransition(baseNumber, {
  duration: 1000,
  transition: TransitionPresets['easeInOutCubic'],
})
```

So it can be better tree shakable and flexible for users to customize. And if they want to change the numbers, they can always use "Go To Definition" to grab them can copy-paste. WDYT? Thanks.
